### ISSUE TITLE
Optimize code coverage publishing in pipelines

### ISSUE THREAD

**Issue by makubacki** [microsoft/mu_devops#267]
When a large number of pipeline runs at once (e.g. pytools pip update), the `PublishCoverage` job in [`Jobs/PrGate.yml`](https://github.com/microsoft/mu_devops/blob/main/Jobs/PrGate.yml#L169) significantly contributes to the overall time for the pipeline to finish.

This makes PRs take much longer to reach a status check finished state and for the overall job queue to drain. Essentially, the pipeline has to queue twice, once for all of the matrix jobs and again for the code coverage publishing job.

This issue tracks optimizing code coverage publishing to reduce the impact on overall pipeline execution time.

For example, a matrix will spawn `N` jobs. At the end of each matrix job checking if all other matrix jobs (`N-1`) are complete, perhaps using the ADO REST API, and then attempting to publish code coverage directly from the job, etc.

**Comment by Javagedes** [comment]
@makubacki My initial impression is that this can decrease the wait time of a PR run if there is an existing backup of runners that need to execute, as the code coverage pipeline is queued in the back. However changing the code coverage to publish for each pipeline will increase the overall backup of all runners because it will add ~8 minutes to each pipeline where as the current implementation only adds ~9 minutes to a signle pipeline. WIth only 30 runners we could easily feel those effects.

Additionally, PublishCodeCoverage@1 has a limitation in which only the first code coverage report added is used. I don't see that limitation with PublishCodeCoverage@2, but that does not necessarily mean it is *not* still a limitation. That is something I would need to investigate.

![image](https://github.com/microsoft/mu_devops/assets/24388509/55025740-7611-42ce-a341-c923fe0a3b95)

**Comment by makubacki** [comment]
> I think a better solution, if it exists (which it probably doesn't), is a configuration in azure devops such that these types of jobs (ones that have dependencies on jobs that have already run) are pushed to the front of the runner queue.
> 
Agree. I'd also prefer to simply prioritize the job if possible.

**Comment by Javagedes** [comment]
I see a Run This Job now button, but no priority settings in the pipeline or configuration in azure.

https://learn.microsoft.com/en-us/azure/devops/release-notes/2020/pipelines/sprint-175-update#run-this-job-next

The only solution someone mentioned is to have a separate agent pool with a runner or two in it, and then in the pipeline use the "demands" config to use that particular agent pool.

**Comment by Javagedes** [comment]
@makubacki My original implementation of the most recent code coverage changes did have the parsing and report manipulation in each of the individual matrix jobs, so if PublishCodeCoverage@2 supports merging reports then it is an easy resolution. Otherwise, we may consider uploading to CodeCov instead, which does merge results. That would work for any public repos but not private.

**Comment by Javagedes** [comment]
Working on this, `PublishCodeCoverageResults@2` does merge coverage reports... however the way it is merged causes the report to no longer lump source files by INF (see [Here](https://dev.azure.com/projectmu/mu/_build/results?buildId=57601&view=codecoverage-tab).

![image](https://github.com/microsoft/mu_devops/assets/24388509/745e2c4a-e7f7-4f67-8ce3-a717ba79d23f)


An additional issue is that containers don't have dotnet in them, so they cannot upload the coverage data as it relies on dotnet
